
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;


namespace CurrentDesk.Models
{

public partial class AccountCurrency
{
    #region Primitive Properties
    

    public virtual int PK_AccountCurrencyID
    {

        get;
        set;

    }


    public virtual int FK_AccountFormTypeID
    {

        get { return _fK_AccountFormTypeID; }
        set
        {

            if (_fK_AccountFormTypeID != value)

            {

                if (L_AccountFormType != null && L_AccountFormType.PK_AccountFormID != value)

                {

                    L_AccountFormType = null;

                }

                _fK_AccountFormTypeID = value;
            }

        }

    }

    private int _fK_AccountFormTypeID;


    public virtual int FK_CurrencyValueID
    {

        get { return _fK_CurrencyValueID; }
        set
        {

            if (_fK_CurrencyValueID != value)

            {

                if (L_CurrencyValue != null && L_CurrencyValue.PK_CurrencyValueID != value)

                {

                    L_CurrencyValue = null;

                }

                _fK_CurrencyValueID = value;
            }

        }

    }

    private int _fK_CurrencyValueID;


    public virtual int FK_OrganizationID
    {

        get { return _fK_OrganizationID; }
        set
        {

            if (_fK_OrganizationID != value)

            {

                if (Organization != null && Organization.PK_OrganizationID != value)

                {

                    Organization = null;

                }

                _fK_OrganizationID = value;
            }

        }

    }

    private int _fK_OrganizationID;

        #endregion

        #region Navigation Properties
    


    public virtual L_AccountFormType L_AccountFormType
    {

        get { return _l_AccountFormType; }
        set
        {
            if (!ReferenceEquals(_l_AccountFormType, value))
            {
                var previousValue = _l_AccountFormType;
                _l_AccountFormType = value;
                FixupL_AccountFormType(previousValue);
            }
        }
    }
    private L_AccountFormType _l_AccountFormType;



    public virtual L_CurrencyValue L_CurrencyValue
    {

        get { return _l_CurrencyValue; }
        set
        {
            if (!ReferenceEquals(_l_CurrencyValue, value))
            {
                var previousValue = _l_CurrencyValue;
                _l_CurrencyValue = value;
                FixupL_CurrencyValue(previousValue);
            }
        }
    }
    private L_CurrencyValue _l_CurrencyValue;



    public virtual ICollection<LiveLead> LiveLeads
    {
        get
        {
            if (_liveLeads == null)
            {

                var newCollection = new FixupCollection<LiveLead>();
                newCollection.CollectionChanged += FixupLiveLeads;
                _liveLeads = newCollection;

            }
            return _liveLeads;
        }
        set
        {

            if (!ReferenceEquals(_liveLeads, value))
            {
                var previousValue = _liveLeads as FixupCollection<LiveLead>;
                if (previousValue != null)
                {
                    previousValue.CollectionChanged -= FixupLiveLeads;
                }
                _liveLeads = value;
                var newValue = value as FixupCollection<LiveLead>;
                if (newValue != null)
                {
                    newValue.CollectionChanged += FixupLiveLeads;
                }
            }

        }
    }
    private ICollection<LiveLead> _liveLeads;



    public virtual ICollection<ManagedAccountProgram> ManagedAccountPrograms
    {
        get
        {
            if (_managedAccountPrograms == null)
            {

                var newCollection = new FixupCollection<ManagedAccountProgram>();
                newCollection.CollectionChanged += FixupManagedAccountPrograms;
                _managedAccountPrograms = newCollection;

            }
            return _managedAccountPrograms;
        }
        set
        {

            if (!ReferenceEquals(_managedAccountPrograms, value))
            {
                var previousValue = _managedAccountPrograms as FixupCollection<ManagedAccountProgram>;
                if (previousValue != null)
                {
                    previousValue.CollectionChanged -= FixupManagedAccountPrograms;
                }
                _managedAccountPrograms = value;
                var newValue = value as FixupCollection<ManagedAccountProgram>;
                if (newValue != null)
                {
                    newValue.CollectionChanged += FixupManagedAccountPrograms;
                }
            }

        }
    }
    private ICollection<ManagedAccountProgram> _managedAccountPrograms;



    public virtual ICollection<DemoLead> DemoLeads
    {
        get
        {
            if (_demoLeads == null)
            {

                var newCollection = new FixupCollection<DemoLead>();
                newCollection.CollectionChanged += FixupDemoLeads;
                _demoLeads = newCollection;

            }
            return _demoLeads;
        }
        set
        {

            if (!ReferenceEquals(_demoLeads, value))
            {
                var previousValue = _demoLeads as FixupCollection<DemoLead>;
                if (previousValue != null)
                {
                    previousValue.CollectionChanged -= FixupDemoLeads;
                }
                _demoLeads = value;
                var newValue = value as FixupCollection<DemoLead>;
                if (newValue != null)
                {
                    newValue.CollectionChanged += FixupDemoLeads;
                }
            }

        }
    }
    private ICollection<DemoLead> _demoLeads;



    public virtual Organization Organization
    {

        get { return _organization; }
        set
        {
            if (!ReferenceEquals(_organization, value))
            {
                var previousValue = _organization;
                _organization = value;
                FixupOrganization(previousValue);
            }
        }
    }
    private Organization _organization;

        #endregion

        #region Association Fixup
    

    private void FixupL_AccountFormType(L_AccountFormType previousValue)
    {

        if (previousValue != null && previousValue.AccountCurrencies.Contains(this))
        {
            previousValue.AccountCurrencies.Remove(this);
        }


        if (L_AccountFormType != null)
        {
            if (!L_AccountFormType.AccountCurrencies.Contains(this))
            {
                L_AccountFormType.AccountCurrencies.Add(this);
            }

            if (FK_AccountFormTypeID != L_AccountFormType.PK_AccountFormID)

            {
                FK_AccountFormTypeID = L_AccountFormType.PK_AccountFormID;
            }

        }

    }


    private void FixupL_CurrencyValue(L_CurrencyValue previousValue)
    {

        if (previousValue != null && previousValue.AccountCurrencies.Contains(this))
        {
            previousValue.AccountCurrencies.Remove(this);
        }


        if (L_CurrencyValue != null)
        {
            if (!L_CurrencyValue.AccountCurrencies.Contains(this))
            {
                L_CurrencyValue.AccountCurrencies.Add(this);
            }

            if (FK_CurrencyValueID != L_CurrencyValue.PK_CurrencyValueID)

            {
                FK_CurrencyValueID = L_CurrencyValue.PK_CurrencyValueID;
            }

        }

    }


    private void FixupOrganization(Organization previousValue)
    {

        if (previousValue != null && previousValue.AccountCurrencies.Contains(this))
        {
            previousValue.AccountCurrencies.Remove(this);
        }


        if (Organization != null)
        {
            if (!Organization.AccountCurrencies.Contains(this))
            {
                Organization.AccountCurrencies.Add(this);
            }

            if (FK_OrganizationID != Organization.PK_OrganizationID)

            {
                FK_OrganizationID = Organization.PK_OrganizationID;
            }

        }

    }


    private void FixupLiveLeads(object sender, NotifyCollectionChangedEventArgs e)
    {
        if (e.NewItems != null)
        {
            foreach (LiveLead item in e.NewItems)
            {

                item.AccountCurrency = this;

            }
        }

        if (e.OldItems != null)
        {
            foreach (LiveLead item in e.OldItems)
            {

                if (ReferenceEquals(item.AccountCurrency, this))
                {
                    item.AccountCurrency = null;
                }

            }
        }
    }


    private void FixupManagedAccountPrograms(object sender, NotifyCollectionChangedEventArgs e)
    {
        if (e.NewItems != null)
        {
            foreach (ManagedAccountProgram item in e.NewItems)
            {

                item.AccountCurrency = this;

            }
        }

        if (e.OldItems != null)
        {
            foreach (ManagedAccountProgram item in e.OldItems)
            {

                if (ReferenceEquals(item.AccountCurrency, this))
                {
                    item.AccountCurrency = null;
                }

            }
        }
    }


    private void FixupDemoLeads(object sender, NotifyCollectionChangedEventArgs e)
    {
        if (e.NewItems != null)
        {
            foreach (DemoLead item in e.NewItems)
            {

                item.AccountCurrency = this;

            }
        }

        if (e.OldItems != null)
        {
            foreach (DemoLead item in e.OldItems)
            {

                if (ReferenceEquals(item.AccountCurrency, this))
                {
                    item.AccountCurrency = null;
                }

            }
        }
    }

        #endregion

    
}

}
