
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;


namespace CurrentDesk.Models
{

public partial class ErrorLog
{
    #region Primitive Properties
    

    public virtual int PK_ErrorID
    {

        get;
        set;

    }


    public virtual Nullable<System.DateTime> LoggedDate
    {

        get;
        set;

    }


    public virtual string Level
    {

        get;
        set;

    }


    public virtual string Logger
    {

        get;
        set;

    }


    public virtual string Message
    {

        get;
        set;

    }


    public virtual string Thread
    {

        get;
        set;

    }


    public virtual string Exception
    {

        get;
        set;

    }


    public virtual string ServerName
    {

        get;
        set;

    }


    public virtual string IpAddress
    {

        get;
        set;

    }


    public virtual string Url
    {

        get;
        set;

    }


    public virtual string Referrer
    {

        get;
        set;

    }


    public virtual string UserName
    {

        get;
        set;

    }


    public virtual string UserAgent
    {

        get;
        set;

    }

        #endregion

    
}

}
