
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;


namespace CurrentDesk.Models
{

public partial class L_AccountTypeValue
{
    #region Primitive Properties
    

    public virtual int PK_AccountTypeValueID
    {

        get;
        set;

    }


    public virtual string AccountTypeValues
    {

        get;
        set;

    }

        #endregion

        #region Navigation Properties
    


    public virtual ICollection<AccountType> AccountTypes
    {
        get
        {
            if (_accountTypes == null)
            {

                var newCollection = new FixupCollection<AccountType>();
                newCollection.CollectionChanged += FixupAccountTypes;
                _accountTypes = newCollection;

            }
            return _accountTypes;
        }
        set
        {

            if (!ReferenceEquals(_accountTypes, value))
            {
                var previousValue = _accountTypes as FixupCollection<AccountType>;
                if (previousValue != null)
                {
                    previousValue.CollectionChanged -= FixupAccountTypes;
                }
                _accountTypes = value;
                var newValue = value as FixupCollection<AccountType>;
                if (newValue != null)
                {
                    newValue.CollectionChanged += FixupAccountTypes;
                }
            }

        }
    }
    private ICollection<AccountType> _accountTypes;

        #endregion

        #region Association Fixup
    

    private void FixupAccountTypes(object sender, NotifyCollectionChangedEventArgs e)
    {
        if (e.NewItems != null)
        {
            foreach (AccountType item in e.NewItems)
            {

                item.L_AccountTypeValue = this;

            }
        }

        if (e.OldItems != null)
        {
            foreach (AccountType item in e.OldItems)
            {

                if (ReferenceEquals(item.L_AccountTypeValue, this))
                {
                    item.L_AccountTypeValue = null;
                }

            }
        }
    }

        #endregion

    
}

}
