
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;


namespace CurrentDesk.Models
{

public partial class L_LiquidAssetsValue
{
    #region Primitive Properties
    

    public virtual int PK_LiquidAssetID
    {

        get;
        set;

    }


    public virtual string LiquidAsset
    {

        get;
        set;

    }

        #endregion

    
}

}
