
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;


namespace CurrentDesk.Models
{

public partial class ProfileActivity
{
    #region Primitive Properties
    

    public virtual int PK_ProfileActivityID
    {

        get;
        set;

    }


    public virtual string ProfileActivityDetails
    {

        get;
        set;

    }


    public virtual Nullable<int> FK_UserActivityID
    {

        get { return _fK_UserActivityID; }
        set
        {

            try
            {
                _settingFK = true;

            if (_fK_UserActivityID != value)

            {

                if (UserActivity != null && UserActivity.PK_UserActivityID != value)

                {

                    UserActivity = null;

                }

                _fK_UserActivityID = value;
            }

            }
            finally
            {
                _settingFK = false;
            }

        }

    }

    private Nullable<int> _fK_UserActivityID;

        #endregion

        #region Navigation Properties
    


    public virtual UserActivity UserActivity
    {

        get { return _userActivity; }
        set
        {
            if (!ReferenceEquals(_userActivity, value))
            {
                var previousValue = _userActivity;
                _userActivity = value;
                FixupUserActivity(previousValue);
            }
        }
    }
    private UserActivity _userActivity;

        #endregion

        #region Association Fixup
    

    private bool _settingFK = false;


    private void FixupUserActivity(UserActivity previousValue)
    {

        if (previousValue != null && previousValue.ProfileActivities.Contains(this))
        {
            previousValue.ProfileActivities.Remove(this);
        }


        if (UserActivity != null)
        {
            if (!UserActivity.ProfileActivities.Contains(this))
            {
                UserActivity.ProfileActivities.Add(this);
            }

            if (FK_UserActivityID != UserActivity.PK_UserActivityID)

            {
                FK_UserActivityID = UserActivity.PK_UserActivityID;
            }

        }

        else if (!_settingFK)

        {

            FK_UserActivityID = null;

        }

    }

        #endregion

    
}

}
