
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;


namespace CurrentDesk.Models
{

public partial class TransferLog
{
    #region Primitive Properties
    

    public virtual int PK_TransferLogID
    {

        get;
        set;

    }


    public virtual Nullable<int> CurrencyID
    {

        get;
        set;

    }


    public virtual Nullable<decimal> Amount
    {

        get;
        set;

    }


    public virtual string TransactionType
    {

        get;
        set;

    }


    public virtual string AccountNumber
    {

        get;
        set;

    }


    public virtual Nullable<System.DateTime> TransactionDateTime
    {

        get;
        set;

    }


    public virtual Nullable<int> FK_TransactionID
    {

        get { return _fK_TransactionID; }
        set
        {

            try
            {
                _settingFK = true;

            if (_fK_TransactionID != value)

            {

                if (Transaction != null && Transaction.PK_TransactionID != value)

                {

                    Transaction = null;

                }

                _fK_TransactionID = value;
            }

            }
            finally
            {
                _settingFK = false;
            }

        }

    }

    private Nullable<int> _fK_TransactionID;


    public virtual int FK_OrganizationID
    {

        get { return _fK_OrganizationID; }
        set
        {

            try
            {
                _settingFK = true;

            if (_fK_OrganizationID != value)

            {

                if (Organization != null && Organization.PK_OrganizationID != value)

                {

                    Organization = null;

                }

                _fK_OrganizationID = value;
            }

            }
            finally
            {
                _settingFK = false;
            }

        }

    }

    private int _fK_OrganizationID;

        #endregion

        #region Navigation Properties
    


    public virtual Transaction Transaction
    {

        get { return _transaction; }
        set
        {
            if (!ReferenceEquals(_transaction, value))
            {
                var previousValue = _transaction;
                _transaction = value;
                FixupTransaction(previousValue);
            }
        }
    }
    private Transaction _transaction;



    public virtual Organization Organization
    {

        get { return _organization; }
        set
        {
            if (!ReferenceEquals(_organization, value))
            {
                var previousValue = _organization;
                _organization = value;
                FixupOrganization(previousValue);
            }
        }
    }
    private Organization _organization;

        #endregion

        #region Association Fixup
    

    private bool _settingFK = false;


    private void FixupTransaction(Transaction previousValue)
    {

        if (previousValue != null && previousValue.TransferLogs.Contains(this))
        {
            previousValue.TransferLogs.Remove(this);
        }


        if (Transaction != null)
        {
            if (!Transaction.TransferLogs.Contains(this))
            {
                Transaction.TransferLogs.Add(this);
            }

            if (FK_TransactionID != Transaction.PK_TransactionID)

            {
                FK_TransactionID = Transaction.PK_TransactionID;
            }

        }

        else if (!_settingFK)

        {

            FK_TransactionID = null;

        }

    }


    private void FixupOrganization(Organization previousValue)
    {

        if (previousValue != null && previousValue.TransferLogs.Contains(this))
        {
            previousValue.TransferLogs.Remove(this);
        }


        if (Organization != null)
        {
            if (!Organization.TransferLogs.Contains(this))
            {
                Organization.TransferLogs.Add(this);
            }

            if (FK_OrganizationID != Organization.PK_OrganizationID)

            {
                FK_OrganizationID = Organization.PK_OrganizationID;
            }

        }

    }

        #endregion

    
}

}
