xcopy "E:\approot\RunTimeLibraries\msvcirt.dll" "%windir%\system32" /y
xcopy "E:\approot\RunTimeLibraries\msvcp100.dll" "%windir%\system32" /y
xcopy "E:\approot\RunTimeLibraries\msvcp100d.dll" "%windir%\system32" /y
xcopy "E:\approot\RunTimeLibraries\msvcp110.dll" "%windir%\system32" /y
xcopy "E:\approot\RunTimeLibraries\msvcp110_clr0400.dll" "%windir%\system32" /y
xcopy "E:\approot\RunTimeLibraries\msvcp110d.dll" "%windir%\system32" /y
xcopy "E:\approot\RunTimeLibraries\msvcp60.dll" "%windir%\system32" /y
xcopy "E:\approot\RunTimeLibraries\msvcr100.dll" "%windir%\system32" /y
xcopy "E:\approot\RunTimeLibraries\msvcr100_clr0400.dll" "%windir%\system32" /y
xcopy "E:\approot\RunTimeLibraries\msvcr100d.dll" "%windir%\system32" /y
xcopy "E:\approot\RunTimeLibraries\msvcr110.dll" "%windir%\system32" /y
xcopy "E:\approot\RunTimeLibraries\msvcr110_clr0400.dll" "%windir%\system32" /y
xcopy "E:\approot\RunTimeLibraries\msvcr110d.dll" "%windir%\system32" /y
xcopy "E:\approot\RunTimeLibraries\msvcrt.dll" "%windir%\system32" /y
xcopy "E:\approot\RunTimeLibraries\mtmanapi.dll" "%windir%\system32" /y
xcopy "E:\approot\RunTimeLibraries\mtmanapi64.dll" "%windir%\system32" /y