using System;
using System.Linq;
using System.Collections.Generic;
using CurrentDesk.Models;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template at 1/2/2013 5:37:12 PM
//	   and this file should not get overridden 
//
//     Add your own data access methods.
// </auto-generated>
//------------------------------------------------------------------------------ 
	
namespace CurrentDesk.Repository.CurrentDesk
{   
	public class AssetManagerBO
	{
        /// <summary>
        /// This function will insert Asset Manager details
        /// </summary>
        /// <returns></returns>
        public void AddAssetManagerDetails(AssetManager newAM)
        {

            try
            {
                using (var unitOfWork = new EFUnitOfWork())
                {
                    var AMDetailsRepo =
                        new AssetManagerRepository(new EFRepository<AssetManager>(), unitOfWork);

                    AMDetailsRepo.Add(newAM);
                    AMDetailsRepo.Save();
                }
            }
            catch(Exception ex)
            {
                CommonErrorLogger.CommonErrorLog(ex, System.Reflection.MethodBase.GetCurrentMethod().Name);
                throw;
            }
        }
		
	}
}