using System;
using System.Linq;
using System.Collections.Generic;
using CurrentDesk.Models;
using System.Data.Objects;
using CurrentDesk.DAL;
using CurrentDesk.Common;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template at 12/25/2012 2:56:22 PM
//	   and this file should not get overridden 
//
//     Add your own data access methods.
// </auto-generated>
//------------------------------------------------------------------------------ 
	
namespace CurrentDesk.Repository.CurrentDesk
{   
	public class CorporateAccountInformationBO
	{
        /// <summary>
        /// This function will insert corporate account details for new client
        /// </summary>
        /// <returns></returns>
        public void AddCorporateAccDetailsForNewClient(CorporateAccountInformation newClient)
        {

            try
            {
                using (var unitOfWork = new EFUnitOfWork())
                {
                    var corporateDetailsRepo =
                        new CorporateAccountInformationRepository(new EFRepository<CorporateAccountInformation>(), unitOfWork);

                    corporateDetailsRepo.Add(newClient);
                    corporateDetailsRepo.Save();
                }
            }
            catch(Exception ex)
            {
                CommonErrorLogger.CommonErrorLog(ex, System.Reflection.MethodBase.GetCurrentMethod().Name);
                throw;
            }
        }

        /// <summary>
        /// This Function Will Get The Company Name
        /// </summary>
        /// <param name="clientID"></param>
        /// <returns></returns>
        public string GetLiveIndividualName(int clientID, LoginAccountType accType)
        {
            try
            {
                using (var unitOfWork = new EFUnitOfWork())
                {
                    var corporateDetailsRepo =
                        new CorporateAccountInformationRepository(new EFRepository<CorporateAccountInformation>(), unitOfWork);

                    ObjectSet<CorporateAccountInformation> corporateObjSet =
                        ((CurrentDeskClientsEntities)corporateDetailsRepo.Repository.UnitOfWork.Context).CorporateAccountInformations;

                    if (accType == LoginAccountType.LiveAccount)
                    {
                        var res = corporateObjSet.Where(ind => ind.FK_ClientID == clientID).FirstOrDefault();
                        return res != null ? res.CompanyName : null;
                    }
                    else if (accType == LoginAccountType.PartnerAccount)
                    {
                        var res = corporateObjSet.Where(ind => ind.FK_IntroducingBrokerID == clientID).FirstOrDefault();
                        return res != null ? res.CompanyName : null;
                    }
                    return string.Empty;
                }
            }
            catch(Exception ex)
            {
                CommonErrorLogger.CommonErrorLog(ex, System.Reflection.MethodBase.GetCurrentMethod().Name);
                throw;
            }
        }

        /// <summary>
        /// This Function Will Get The Company Name
        /// </summary>
        /// <param name="clientID"></param>
        /// <returns></returns>
        public string GetPartnerIndividualName(int introducingBrokerID)
        {
            try
            {
                using (var unitOfWork = new EFUnitOfWork())
                {
                    var corporateDetailsRepo =
                        new CorporateAccountInformationRepository(new EFRepository<CorporateAccountInformation>(), unitOfWork);

                    ObjectSet<CorporateAccountInformation> corporateObjSet =
                        ((CurrentDeskClientsEntities)corporateDetailsRepo.Repository.UnitOfWork.Context).CorporateAccountInformations;

                    var res = corporateObjSet.Where(ind => ind.FK_IntroducingBrokerID == introducingBrokerID).FirstOrDefault();

                    return res != null ? res.CompanyName : null;
                }
            }
            catch(Exception ex)
            {
                CommonErrorLogger.CommonErrorLog(ex, System.Reflection.MethodBase.GetCurrentMethod().Name);
                throw;
            }
        }

        /// <summary>
        /// This method returns corporate details of a particular client
        /// </summary>
        /// <param name="clientID">clientID</param>
        /// <returns></returns>
        public CorporateAccountInformation GetCorporateAccountDetails(int clientID)
        {
            try
            {
                using (var unitOfWork = new EFUnitOfWork())
                {
                    var corporateDetailsRepo =
                        new CorporateAccountInformationRepository(new EFRepository<CorporateAccountInformation>(), unitOfWork);

                    ObjectSet<CorporateAccountInformation> corporateObjSet =
                        ((CurrentDeskClientsEntities)corporateDetailsRepo.Repository.UnitOfWork.Context).CorporateAccountInformations;


                    return corporateObjSet.Where(corp => corp.FK_ClientID == clientID).FirstOrDefault();
                }
            }
            catch (Exception ex)
            {
                CommonErrorLogger.CommonErrorLog(ex, System.Reflection.MethodBase.GetCurrentMethod().Name);
                throw;
            }
        }
		
	}
}