//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Objects;

namespace TestingDAL
{
    public partial class CurrentDeskClientsEntities : DbContext
    {
        public CurrentDeskClientsEntities()
            : this(false) { }
    
        public CurrentDeskClientsEntities(bool proxyCreationEnabled)	    
            : base("name=CurrentDeskClientsEntities")
        {
            this.Configuration.ProxyCreationEnabled = proxyCreationEnabled;
        }
    
        public CurrentDeskClientsEntities(string connectionString)
          : this(connectionString, false) { }
    
        public CurrentDeskClientsEntities(string connectionString, bool proxyCreationEnabled)
            : base(connectionString)
        {
            this.Configuration.ProxyCreationEnabled = proxyCreationEnabled;
        }	
    
        public ObjectContext ObjectContext
        {
          get { return ((IObjectContextAdapter)this).ObjectContext; }
        }
    
    	protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    	
        public DbSet<AccountCurrency> AccountCurrencies { get; set; }
        public DbSet<AccountType> AccountTypes { get; set; }
        public DbSet<Client> Clients { get; set; }
        public DbSet<ClientInformation> ClientInformations { get; set; }
        public DbSet<CorporateAccountInformation> CorporateAccountInformations { get; set; }
        public DbSet<DemoLead> DemoLeads { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<IndividualAccountInformation> IndividualAccountInformations { get; set; }
        public DbSet<IntroducingBroker> IntroducingBrokers { get; set; }
        public DbSet<JointAccountInformation> JointAccountInformations { get; set; }
        public DbSet<L_Account> L_Account { get; set; }
        public DbSet<L_AccountFormType> L_AccountFormType { get; set; }
        public DbSet<L_AccountTypeValue> L_AccountTypeValue { get; set; }
        public DbSet<L_AnnualIncomeValue> L_AnnualIncomeValue { get; set; }
        public DbSet<L_CommissionIncrementValue> L_CommissionIncrementValue { get; set; }
        public DbSet<L_CompanyTypeValue> L_CompanyTypeValue { get; set; }
        public DbSet<L_Country> L_Country { get; set; }
        public DbSet<L_CurrencyValue> L_CurrencyValue { get; set; }
        public DbSet<L_IDInformationType> L_IDInformationType { get; set; }
        public DbSet<L_InitialInvestment> L_InitialInvestment { get; set; }
        public DbSet<L_Languages> L_Languages { get; set; }
        public DbSet<L_LiquidAssetsValue> L_LiquidAssetsValue { get; set; }
        public DbSet<L_NetWorthEuros> L_NetWorthEuros { get; set; }
        public DbSet<L_RecievingBank> L_RecievingBank { get; set; }
        public DbSet<L_TicketSize> L_TicketSize { get; set; }
        public DbSet<L_TradingExperience> L_TradingExperience { get; set; }
        public DbSet<L_TradingPlatformValues> L_TradingPlatformValues { get; set; }
        public DbSet<L_TrusteeTypeValue> L_TrusteeTypeValue { get; set; }
        public DbSet<L_WidenSpreadsValue> L_WidenSpreadsValue { get; set; }
        public DbSet<LeadNote> LeadNotes { get; set; }
        public DbSet<LiveLead> LiveLeads { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<TradingPlatform> TradingPlatforms { get; set; }
        public DbSet<TrustAccountInformation> TrustAccountInformations { get; set; }
    }
}
