//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace TestingDAL
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Client))]
    [KnownType(typeof(L_IDInformationType))]
    [KnownType(typeof(L_Country))]
    public partial class IndividualAccountInformation
    {
        [DataMember]
        public int PK_IndividualAccountID { get; set; }
        [DataMember]
        public string Title { get; set; }
        [DataMember]
        public string FirstName { get; set; }
        [DataMember]
        public string MiddleName { get; set; }
        [DataMember]
        public string LastName { get; set; }
        [DataMember]
        public Nullable<System.DateTime> BirthDate { get; set; }
        [DataMember]
        public Nullable<bool> Gender { get; set; }
        [DataMember]
        public Nullable<int> FK_CitizenShipCountryID { get; set; }
        [DataMember]
        public Nullable<int> FK_IDInformationID { get; set; }
        [DataMember]
        public string IDNumber { get; set; }
        [DataMember]
        public int FK_ResidenceCountryID { get; set; }
        [DataMember]
        public string ResidentialAddress { get; set; }
        [DataMember]
        public string ResidentialAddressCity { get; set; }
        [DataMember]
        public Nullable<int> FK_ResidentialAddressCountryID { get; set; }
        [DataMember]
        public string ResidentialAddressPostalCode { get; set; }
        [DataMember]
        public Nullable<int> MonthsAtCurrentAddress { get; set; }
        [DataMember]
        public string PreviousAddress { get; set; }
        [DataMember]
        public string PreviousAddressCity { get; set; }
        [DataMember]
        public Nullable<int> FK_PreviousAddressCounrtyID { get; set; }
        [DataMember]
        public string PreviousAddressPostalCode { get; set; }
        [DataMember]
        public string TelephoneNumber { get; set; }
        [DataMember]
        public string MobileNumber { get; set; }
        [DataMember]
        public string EmailAddress { get; set; }
        [DataMember]
        public Nullable<int> FK_ClientID { get; set; }
    
        [DataMember]
        public virtual Client Client { get; set; }
        [DataMember]
        public virtual L_IDInformationType L_IDInformationType { get; set; }
        [DataMember]
        public virtual L_Country L_Country { get; set; }
        [DataMember]
        public virtual L_Country L_Country1 { get; set; }
        [DataMember]
        public virtual L_Country L_Country2 { get; set; }
        [DataMember]
        public virtual L_Country L_Country3 { get; set; }
    }
    
}
