//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace TestingDAL
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(AccountType))]
    public partial class L_AccountTypeValue
    {
        public L_AccountTypeValue()
        {
            this.AccountTypes = new HashSet<AccountType>();
        }
    
        [DataMember]
        public int PK_AccountTypeValueID { get; set; }
        [DataMember]
        public string AccountTypeValues { get; set; }
    
        [DataMember]
        public virtual ICollection<AccountType> AccountTypes { get; set; }
    }
    
}
