//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace TestingDAL
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(CorporateAccountInformation))]
    [KnownType(typeof(TrustAccountInformation))]
    public partial class L_CompanyTypeValue
    {
        public L_CompanyTypeValue()
        {
            this.CorporateAccountInformations = new HashSet<CorporateAccountInformation>();
            this.TrustAccountInformations = new HashSet<TrustAccountInformation>();
        }
    
        [DataMember]
        public int PK_CompanyTypeID { get; set; }
        [DataMember]
        public string CompanyType { get; set; }
    
        [DataMember]
        public virtual ICollection<CorporateAccountInformation> CorporateAccountInformations { get; set; }
        [DataMember]
        public virtual ICollection<TrustAccountInformation> TrustAccountInformations { get; set; }
    }
    
}
