//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace TestingDAL
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(CorporateAccountInformation))]
    [KnownType(typeof(IndividualAccountInformation))]
    [KnownType(typeof(JointAccountInformation))]
    [KnownType(typeof(TrustAccountInformation))]
    public partial class L_IDInformationType
    {
        public L_IDInformationType()
        {
            this.CorporateAccountInformations = new HashSet<CorporateAccountInformation>();
            this.IndividualAccountInformations = new HashSet<IndividualAccountInformation>();
            this.JointAccountInformations = new HashSet<JointAccountInformation>();
            this.JointAccountInformations1 = new HashSet<JointAccountInformation>();
            this.TrustAccountInformations = new HashSet<TrustAccountInformation>();
            this.TrustAccountInformations1 = new HashSet<TrustAccountInformation>();
        }
    
        [DataMember]
        public int PK_IDTypeID { get; set; }
        [DataMember]
        public string IDValue { get; set; }
    
        [DataMember]
        public virtual ICollection<CorporateAccountInformation> CorporateAccountInformations { get; set; }
        [DataMember]
        public virtual ICollection<IndividualAccountInformation> IndividualAccountInformations { get; set; }
        [DataMember]
        public virtual ICollection<JointAccountInformation> JointAccountInformations { get; set; }
        [DataMember]
        public virtual ICollection<JointAccountInformation> JointAccountInformations1 { get; set; }
        [DataMember]
        public virtual ICollection<TrustAccountInformation> TrustAccountInformations { get; set; }
        [DataMember]
        public virtual ICollection<TrustAccountInformation> TrustAccountInformations1 { get; set; }
    }
    
}
