//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace TestingDAL
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(DemoLead))]
    public partial class L_InitialInvestment
    {
        public L_InitialInvestment()
        {
            this.DemoLeads = new HashSet<DemoLead>();
        }
    
        [DataMember]
        public int PK_InitialInvestmentID { get; set; }
        [DataMember]
        public string InvestmentValue { get; set; }
    
        [DataMember]
        public virtual ICollection<DemoLead> DemoLeads { get; set; }
    }
    
}
