//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace TestingDAL
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Client))]
    public partial class L_RecievingBank
    {
        public L_RecievingBank()
        {
            this.Clients = new HashSet<Client>();
        }
    
        [DataMember]
        public int PK_RecievingBankID { get; set; }
        [DataMember]
        public string RecievingBankName { get; set; }
    
        [DataMember]
        public virtual ICollection<Client> Clients { get; set; }
    }
    
}
