//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace TestingDAL
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Client))]
    [KnownType(typeof(L_CompanyTypeValue))]
    [KnownType(typeof(L_Country))]
    [KnownType(typeof(L_IDInformationType))]
    [KnownType(typeof(L_TrusteeTypeValue))]
    public partial class TrustAccountInformation
    {
        [DataMember]
        public int PK_TrustAccountID { get; set; }
        [DataMember]
        public Nullable<int> FK_TrusteeTypeID { get; set; }
        [DataMember]
        public string TrustAddress { get; set; }
        [DataMember]
        public string TrustCity { get; set; }
        [DataMember]
        public Nullable<int> FK_TrustCountryID { get; set; }
        [DataMember]
        public string TrustPostalCode { get; set; }
        [DataMember]
        public string TrusteeCompanyName { get; set; }
        [DataMember]
        public Nullable<int> FK_TrusteeCompanyTypeID { get; set; }
        [DataMember]
        public string TrusteeAddress { get; set; }
        [DataMember]
        public string TrusteeCity { get; set; }
        [DataMember]
        public Nullable<int> FK_TrusteeCountryID { get; set; }
        [DataMember]
        public string TrusteePostalCode { get; set; }
        [DataMember]
        public string TrusteeAuthOfficerTitle { get; set; }
        [DataMember]
        public string TrusteeAuthOfficerFirstName { get; set; }
        [DataMember]
        public string TrusteeAuthOfficerLastName { get; set; }
        [DataMember]
        public string TrusteeAuthOfficerMiddleName { get; set; }
        [DataMember]
        public Nullable<System.DateTime> TrusteeAuthOfficerBirthDate { get; set; }
        [DataMember]
        public Nullable<bool> TrusteeAuthOfficerGender { get; set; }
        [DataMember]
        public Nullable<int> FK_TrusteeAuthOfficerCitizenshipCountryID { get; set; }
        [DataMember]
        public Nullable<int> FK_TrusteeAuthOfficerIDType { get; set; }
        [DataMember]
        public string TrusteeAuthOfficerIDNumber { get; set; }
        [DataMember]
        public Nullable<int> FK_TrusteeAuthOfficerResidenceCountryID { get; set; }
        [DataMember]
        public string TrusteeAuthOfficerAddrerss { get; set; }
        [DataMember]
        public string TrusteeAuthOfficerCity { get; set; }
        [DataMember]
        public Nullable<int> FK_TrusteeAuthOfficerCountryID { get; set; }
        [DataMember]
        public string TrusteeAuthOfficerPostalCode { get; set; }
        [DataMember]
        public string TrusteeAuthOfficerTelephoneNumber { get; set; }
        [DataMember]
        public string TrusteeAuthOfficerMobileNumber { get; set; }
        [DataMember]
        public string TrusteeAuthOfficerEmailAddress { get; set; }
        [DataMember]
        public Nullable<int> FK_ClientID { get; set; }
        [DataMember]
        public string TrusteeIndividualTitle { get; set; }
        [DataMember]
        public string TrusteeIndividualFirstName { get; set; }
        [DataMember]
        public string TrusteeIndividualLastName { get; set; }
        [DataMember]
        public string TrusteeIndividualMiddleName { get; set; }
        [DataMember]
        public Nullable<System.DateTime> TrusteeIndividualBirthDate { get; set; }
        [DataMember]
        public Nullable<bool> TrusteeIndividualGender { get; set; }
        [DataMember]
        public Nullable<int> FK_TrusteeIndividualCitizenshipID { get; set; }
        [DataMember]
        public Nullable<int> FK_TrusteeIndividualIDTypeId { get; set; }
        [DataMember]
        public string TrusteeIndividualIDNumber { get; set; }
        [DataMember]
        public Nullable<int> FK_TrusteeIndividualResidenceCountryID { get; set; }
        [DataMember]
        public string TrusteeIndividualResidentialAddress { get; set; }
        [DataMember]
        public string TrusteeIndividualResidentialCity { get; set; }
        [DataMember]
        public Nullable<int> FK_TrusteeIndividualResidentialCountryID { get; set; }
        [DataMember]
        public string TrusteeIndividualResidentialPostalCode { get; set; }
        [DataMember]
        public Nullable<int> TrusteeIndividualTotalMonthsAtAddress { get; set; }
        [DataMember]
        public string TrusteeIndividualPreviousAddress { get; set; }
        [DataMember]
        public string TrusteeIndividualPreviousCity { get; set; }
        [DataMember]
        public Nullable<int> FK_TrusteeIndividualPreviousCountryID { get; set; }
        [DataMember]
        public string TrusteeIndividualPreviousPostalCode { get; set; }
        [DataMember]
        public string TrusteeIndividualTelephoneNumber { get; set; }
        [DataMember]
        public string TrusteeIndividualMobileNumber { get; set; }
        [DataMember]
        public string TrusteeIndividualEmailAddress { get; set; }
    
        [DataMember]
        public virtual Client Client { get; set; }
        [DataMember]
        public virtual L_CompanyTypeValue L_CompanyTypeValue { get; set; }
        [DataMember]
        public virtual L_Country L_Country { get; set; }
        [DataMember]
        public virtual L_Country L_Country1 { get; set; }
        [DataMember]
        public virtual L_Country L_Country2 { get; set; }
        [DataMember]
        public virtual L_Country L_Country3 { get; set; }
        [DataMember]
        public virtual L_Country L_Country4 { get; set; }
        [DataMember]
        public virtual L_Country L_Country5 { get; set; }
        [DataMember]
        public virtual L_Country L_Country6 { get; set; }
        [DataMember]
        public virtual L_Country L_Country7 { get; set; }
        [DataMember]
        public virtual L_Country L_Country8 { get; set; }
        [DataMember]
        public virtual L_IDInformationType L_IDInformationType { get; set; }
        [DataMember]
        public virtual L_IDInformationType L_IDInformationType1 { get; set; }
        [DataMember]
        public virtual L_TrusteeTypeValue L_TrusteeTypeValue { get; set; }
    }
    
}
